version: '3.8'
services:
  database:
    image: postgres
    container_name: database_tracktoo
    restart: always
    environment:
      - POSTGRES_DB=tracktoo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '65432:5432'
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
  